### ISSUE TITLE
[Error: cannot inherit from final ImageSource] after update react-native to 0.75.0

### ISSUE THREAD

**Issue by Ubaid81** [react-native-tvos/react-native-tvos#775]
Hi,  I have updated react-native-tvos to the latest 0.75.0 version and now have got such errors after executing run android build command.

```
/Users/ubaid/x/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:72: error: isResource() in FastImageSource cannot override isResource() in ImageSource
    public boolean isResource() {
                   ^
  overridden method is final
/Users/ubaid/x/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:101: error: getUri() in FastImageSource cannot override getUri() in ImageSource
    public Uri getUri() {
```
    
    On look up I found this is already fixed in react-native :: https://github.com/facebook/react-native/pull/46152
    
    By when can we expect the tvos to point react-native: 0.75.2 ?
    
    Thanks for the tvos support!

**Comment by douglowder** [comment]
Just released 0.75.2-0 👍 

https://github.com/react-native-tvos/react-native-tvos/discussions/776

**Comment by therbta** [comment]
Using 0.75.2:

```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/rbt/Desktop/ReactNative/veaoffice/node_modules/@react-native-async-storage/async-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
/Users/rbt/Desktop/ReactNative/veaoffice/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:72: error: isResource() in FastImageSource cannot override isResource() in ImageSource public boolean isResource() { ^ overridden method is final
/Users/rbt/Desktop/ReactNative/veaoffice/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:101: error: getUri() in FastImageSource cannot override getUri() in ImageSource public Uri getUri() { ^ overridden method is final
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-fast-image:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details. * Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights. BUILD FAILED in 5s.
info Run CLI with --verbose flag for more details.
```

**Comment by douglowder** [comment]
> Using 0.75.2:
> 
> 
> 
> ```
> 
> /Users/yyyy/Desktop/ReactNative/xxxx/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:72: error: isResource() in FastImageSource cannot override isResource() in ImageSource public boolean isResource() { ^ overridden method is final
> 
> /Users/yyyy/Desktop/ReactNative/xxxx/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:101: error: getUri() in FastImageSource cannot override getUri() in ImageSource public Uri getUri() { ^ overridden method is final
> 
> 
> 
> ```

@therbta it is not clear how you arrived at this state. That looks like a bug in react-native-fast-image. Please provide a way to reproduce this issue.
