### ISSUE TITLE
Compilation error on iOS (not tvOS)

### ISSUE THREAD

**Issue by karmatys8** [react-native-tvos/react-native-tvos#916]
## Description

I am working in a project which has a monorepo in which we are using `react-native-tvos` for both tv and mobile. While upgrading from 0.77.1-0 to 0.79.1-0 I got an compilation error on iOS. It is caused by the fact that in RCTTVNaviagationEventEmitter we import dependencies conditionally via `#if TARGET_OS_TV`, however, we define methods which depend on them without this condition.

This bug was introduced in https://github.com/react-native-tvos/react-native-tvos/pull/910

### Error message

From xCode as it is more readable.

```
In file included from /Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:14:
/Users/konrad/work/sandbox/tvOSrepro/ios/Pods/Headers/Public/React-RCTFBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h:2021:11: warning: duplicate protocol definition of 'NativeTVNavigationEventEmitterSpec' is ignored [-Wduplicate-protocol]
 2021 | @protocol NativeTVNavigationEventEmitterSpec <RCTBridgeModule, RCTTurboModule>
      |           ^
In file included from /Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:8:
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.h:10:11: note: previous definition is here
   10 | @protocol NativeTVNavigationEventEmitterSpec <RCTBridgeModule, RCTTurboModule>
      |           ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:64:6: error: use of undeclared identifier 'RCTTVRemoteHandler'
   64 |     [RCTTVRemoteHandler setUseMenuKey:YES];
      |      ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:65:64: error: use of undeclared identifier 'RCTTVEnableMenuKeyNotification'
   65 |     [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVEnableMenuKeyNotification object:nil];
      |                                                                ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:70:6: error: use of undeclared identifier 'RCTTVRemoteHandler'
   70 |     [RCTTVRemoteHandler setUseMenuKey:NO];
      |      ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:71:64: error: use of undeclared identifier 'RCTTVDisableMenuKeyNotification'
   71 |     [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVDisableMenuKeyNotification object:nil];
      |                                                                ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:76:6: error: use of undeclared identifier 'RCTTVRemoteHandler'
   76 |     [RCTTVRemoteHandler setUsePanGesture:YES];
      |      ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:77:64: error: use of undeclared identifier 'RCTTVEnablePanGestureNotification'
   77 |     [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVEnablePanGestureNotification object:nil];
      |                                                                ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:82:6: error: use of undeclared identifier 'RCTTVRemoteHandler'
   82 |     [RCTTVRemoteHandler setUsePanGesture:NO];
      |      ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:83:64: error: use of undeclared identifier 'RCTTVDisablePanGestureNotification'
   83 |     [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVDisablePanGestureNotification object:nil];
      |                                                                ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:87:4: error: use of undeclared identifier 'RCTTVRemoteHandler'
   87 |   [RCTTVRemoteHandler setGestureHandlersCancelTouches:YES];
      |    ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:88:62: error: use of undeclared identifier 'RCTTVEnableGestureHandlersCancelTouchesNotification'
   88 |   [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVEnableGestureHandlersCancelTouchesNotification object:nil];
      |                                                              ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:92:4: error: use of undeclared identifier 'RCTTVRemoteHandler'
   92 |   [RCTTVRemoteHandler setGestureHandlersCancelTouches:NO];
      |    ^
/Users/konrad/work/sandbox/tvOSrepro/node_modules/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm:93:62: error: use of undeclared identifier 'RCTTVDisableGestureHandlersCancelTouchesNotification'
   93 |   [[NSNotificationCenter defaultCenter] postNotificationName:RCTTVDisableGestureHandlersCancelTouchesNotification object:nil];
      |                                                              ^
```

### GitHub repository

https://github.com/karmatys8/rn-tvos-repro

### Steps to reproduce

1. `git clone https://github.com/karmatys8/rn-tvos-repro.git`
2. `cd rn-tvos-repro`
2. `npm i`
3. `cd ios`
3. `pod install`
4. `cd ..`
5. `npm run ios`

Here is a single command to copy: 
```
git clone https://github.com/karmatys8/rn-tvos-repro.git && cd rn-tvos-repro && npm i && cd ios && pod install && cd .. && npm run ios
```

## Solution/patch

I am not sure if this is correct solution going forward, but it worked for me as a quick fix.

[react-native+0.79.1-0.patch](https://github.com/user-attachments/files/19867110/react-native%2B0.79.1-0.patch)

I am open to work on a more concrete solution.

**Comment by douglowder** [comment]
You are correct. I fixed this a few days ago in https://github.com/react-native-tvos/react-native-tvos/commit/cf829c90851d0d4f0fb131712e3773f25519a11b in the 0.79 branch, and that fix will be in the next release.
